version: "3.8"

networks:
  wan:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"

services:
 kali:
  image: itmdir/itm_dir_images:kalibasic
  network_mode: none
  container_name: "kali"
  tty: true
  dns:
   - 8.8.8.8
   - 8.8.4.4

 workstation:
  image: itmdir/itm_dir_images:workstation
  network_mode: none
  container_name: "workstation"
  tty: true
  dns:
   - 8.8.8.8
   - 8.8.4.4

 server:
  image: itmdir/itm_dir_images:VulnServer
  network_mode: none
  container_name: "server"
  command: ["bash"]
  tty: true
  #sh -c /bin/services.sh && bash
  dns:
   - 8.8.8.8
   - 8.8.4.4

 gateway:
  image: itmdir/itm_dir_images:vyos_router
  container_name: "gateway"
  networks:
   wan:
    ipv4_address: 172.16.0.2
  command: ["/sbin/init"]
  privileged: true

 nmonitor:
  image: itmdir/itm_dir_images:ZeekMon
  container_name: "nmonitor"
  network_mode: none
  privileged: true
  tty: true
